name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - master  # Change this if deploying from a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t bathapudi/smartdatatraining:latest .
        docker push bathapudi/smartdatatraining:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          docker login -u  bathapudi -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/smartdatatraining:latest
          docker stop docker-deploy-container || true
          docker rm docker-deploy-container || true
          docker run -d --name docker-deploy-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/smartdatatraining:latest
        EOF
