name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - master  # Change this if deploying from a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
        echo "EC2_USER=${{ secrets.EC2_USER }}" >> $GITHUB_ENV
        echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t "$DOCKER_USERNAME"/smartdatatraining:latest .
        docker push "$DOCKER_USERNAME"/smartdatatraining:latest

    - name: Set up SSH for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
          set -e
          echo "Logging in to Docker on EC2..."
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          echo "Pulling and deploying the Docker container..."
          docker pull $DOCKER_USERNAME/smartdatatraining:latest
          docker stop docker-deploy-container || true
          docker rm docker-deploy-container || true
          docker run -d --name docker-deploy-container -p 8080:8080 $DOCKER_USERNAME/smartdatatraining:latest
          echo "Deployment completed!"
        EOF
